### ISSUE TITLE
Roland DXY-1300

### ISSUE THREAD

**Issue by koraysels** [xHain-hackspace/PlotterFeeder#4]
Hi man, \
i have a roland DXY-1350 (same as DXY-1300) which i am currently controlling with a serial<>Usb cable on my mac with the awesome (chiplotle)[http://sites.music.columbia.edu/cmc/chiplotle/] 

I was wondering if the ESP-32 could directly interface with the serial port ? or why did you need the level shifters?

**Comment by arglurgl** [comment]
Hey @koraysels 
the converter is needed because RS-232 uses voltages that the ESP can not produce. You need negativ and positive voltages eg +12V and -12V, or +3V and -3V, see https://en.wikipedia.org/wiki/RS-232#Voltage_levels . The ESP can only do 0V and 3.3V Volt which works on some RS-232 devices, but is not in standard specification and especially for our plotter it does not work. I hope this answers your question. Feel free to reopen if needed.
